linters:
  enable:
    - thelper
    - gofumpt
    - tparallel
    - unconvert
    - unparam
    - revive

# it weirdly fails when running in github actions on interface composition.
issues:
  exclude-rules:
  - path: ui/parameter.go
    linters:
    - typecheck