linters:
  enable:
    - thelper
    - gofumpt
    - tparallel
    - unconvert
    - unparam
    - revive
  disable:
    - typecheck # it weirdly fails when running in github actions on interface composition.